### ISSUE TITLE
RFE: Caching support for Dockerfile content

### ISSUE THREAD

**Issue by bkabrda** [DBuildService/dockerfile-parse#1]
As explained in https://github.com/projectatomic/osbs-client/issues/200, it'd be great if `DockerfileParser` could cache `Dockerfile` content when instantiated.
Since I think the purpose of your library is not only to read existing Dockerfiles, but also to create new Dockerfiles, this can't be done automatically by constructor (i.e. I can create a `DockerfileParser` instance with a path to not-yet-existing Dockerfile, add the contents and then dump it).
So I think the best course of action would be to add an argument to the constructor, something like `cache_content=False`. If this is `True`, Dockerfile content would get cached and `DockerfileParser` would then operate on the cached data. With `False`, everything would work pretty much the same way as it does now.

**Comment by jpopelka** [comment]
@bkabrda please check #3  whether it looks like what you expect.
