### ISSUE TITLE
Rename label?

### ISSUE THREAD

**Issue by lcarva** [DBuildService/dockerfile-parse#18]
What's the best way to rename some labels in the Dockerfile?

For example, transform this:
```
FROM fedora
LABEL NAME="spam"
CMD bash
```

into this:
```
FROM fedora
LABEL name="spam"
CMD bash
```

I've tried deleting the label and adding a new one, but that always adds it to the end of the file, which is not desired for my use case.

**Comment by twaugh** [comment]
Probably the best thing to do is to examine the `structure` attribute and reconstruct a new Dockerfile from that, replacing strings as needed.

For instance, you could copy the `structure` attribute, then loop over each item looking for LABEL instructions. When you find one, you could replace the label names in the content fields. Finally, you could concatenate all the content fields (plus newlines) together.

**Comment by lcarva** [comment]
In order to preserve comments in Dockerfile, I had to use a combination of `structure` and `lines`.
Essentially, iterate over each `structure`, but modify the corresponding `lines` if needed.
