### ISSUE TITLE
Should accept dict representing environment vars inherited from parent

### ISSUE THREAD

**Issue by twaugh** [DBuildService/dockerfile-parse#20]
When substituting environment variables, the environment is assumed to be empty at the start. This is not the case for images that inherited from anything other than `scratch`.

The constructor should accept an optional dict parameter `parent_env`, and this should be copied and used as the starting environment variable when parsing the Dockerfile.

**Comment by maxamillion** [comment]
https://github.com/DBuildService/dockerfile-parse/pull/21
https://github.com/projectatomic/atomic-reactor/pull/586

**Comment by twaugh** [comment]
Fixed via #21.
