### ISSUE TITLE
Version 0.0.6 not installable via pip

### ISSUE THREAD

**Issue by mterrel** [DBuildService/dockerfile-parse#29]
I'd like to use the new fileobj feature in 0.0.6, but I can't seem to get pip to install it from pypi:
```
# pip install dockerfile-parse==0.0.6
Collecting dockerfile-parse==0.0.6
  Could not find a version that satisfies the requirement dockerfile-parse==0.0.6 (from versions: 0.0.3, 0.0.4, 0.0.5)
No matching distribution found for dockerfile-parse==0.0.6
```
Installing without specifying version gives 0.0.5:
```
# pip install dockerfile-parseCollecting dockerfile-parse
Installing collected packages: dockerfile-parse
Successfully installed dockerfile-parse-0.0.5
```
But searching indicates that 0.0.6 is latest(??):
```
# pip search dockerfile-parse
[...trimmed output...]
dockerfile-parse (0.0.6)                - Python library for Dockerfile
                                          manipulation
  INSTALLED: 0.0.5
  LATEST:    0.0.6
```
Although I can install from source, I'd like to install direct from pypi if possible.  Thanks in advance for any help!

**Comment by lachmanfrantisek** [comment]
I've tried it as well, but a new version can be downloaded only for *python3*. It would be nice to have the new version for both versions on PyPI.

**Comment by mterrel** [comment]
Ah, that is probably the issue.  I'm using python 2.7 at the moment.

**Comment by lachmanfrantisek** [comment]
The new version is *python2.7* compatible, meantime you can try version from here.

**Comment by twaugh** [comment]
Apologies -- I've published using 'sdist' on PyPI now. Could you please try again?

**Comment by lachmanfrantisek** [comment]
Thank you. For me, it works both for *python2.7* and *python3.5*.

**Comment by mterrel** [comment]
Works for me too.  Thanks for the quick response!
