### ISSUE TITLE
ENV/LABEL is not parsed properly

### ISSUE THREAD

**Issue by lachmanfrantisek** [DBuildService/dockerfile-parse#34]
The quotes escaping when parsing `ENV`/`LABEL` is not handled properly.

- Example Dockerfile:
```dockerfile
FROM fedora:25
ENV x="a b 'c'"
ENV y="'d' e 'f g'"
LABEL n=$x m="$y" o='$x $y'
```

- Envs are as expected:
```python
{
    'x': "a b 'c'",
    'y': "'d' e 'f g'"
}
```

- Labels:
```python
{
    'n': 'a',
    'b': '',
    'c': '',
    'm': "'d' e 'f g'",
    'o': '$x $y'
}
expected = {
    "m": "'d' e 'f g'",
    "n": "a b 'c'",
    "o": "$x $y"
}
```

**Comment by TomasTomecek** [comment]
Wow, I didn't know it's meant to work like that :o

**Comment by lkolacek** [comment]
@lcarva I tested this in https://brewweb.stage.engineering.redhat.com/brew/taskinfo?taskID=20216421
and worked fine for me. See labels in: http://pastebin.test.redhat.com/577659

**Comment by lcarva** [comment]
Relevant snippet from @lkolacek's pastebin:
```
"Labels": {
  "m": "'d' e 'f g'",
  "n": "a b 'c'",
  "o": "$x $y"
}
...
"Env": [
  "x=a b 'c'",
  "y='d' e 'f g'"
]
```
