### ISSUE TITLE
DockerfileParse does not handle cache_content properly

### ISSUE THREAD

**Issue by phracek** [DBuildService/dockerfile-parse#39]
In our project meta-test-family (https://github.com/fedora-modularity/meta-test-family), used for testing containers, we parse Dockerfile and sometimes rendered, named e.g. Dockerfile.rendered.

Unfortunately there is a bug, from my point of view:

~~~
from dockerfile_parse import DockerfileParser

# dockerfile refers to Dockerfile.rendered and Dockerfile itself looks like https://github.com/container-images/memcached/blob/master/Dockerfile
with open(dockerfile, 'r') as f:
       cached_content = f.readlines()
dfp = DockerfileParser(path=os.path.dirname(dockerfile), cache_content=cached_content)
for struct in dfp.structure:
    print(struct)
~~~

This prints Dockerfile and not Dockerfile.rendered.
I guess, bug is here https://github.com/DBuildService/dockerfile-parse/blob/master/dockerfile_parse/parser.py#L176
Before with there should be
~~~
if cache_content:
    self.cached_content = cache_content
else:
    with ....
~~~

I will sent PR for it.

**Comment by TomasTomecek** [comment]
`cache_content` is bool and indicates whether the dockerfile content should be cached, but doesn't store it.

I think that the bug is that you are not able to select the Dockerfile name.

Does this work for you?

```python
In [1]: with open("./Dockerfile.template", 'r') as f:
   ...:     dfp = DockerfileParser(fileobj=f)
   ...:     print(dfp.structure)
   ...:
   ...:
[{'instruction': 'FROM', 'startline': 0, 'endline': 0, 'content': 'FROM {{ config.docke...
```

**Comment by phracek** [comment]
Upps, yeah it works for me. Thx.

**Comment by TomasTomecek** [comment]
That feature was added in [0.0.6](https://github.com/DBuildService/dockerfile-parse/releases/tag/0.0.6). Looks like we should update the package in Fedora.

**Comment by TomasTomecek** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-6c37c21b5b
https://bodhi.fedoraproject.org/updates/FEDORA-2017-2bcc0e39df

**Comment by twaugh** [comment]
OK to close this issue?

**Comment by phracek** [comment]
Yeah. Closing issue
