### ISSUE TITLE
Cannot modify content if using fileobj

### ISSUE THREAD

**Issue by c4tz** [DBuildService/dockerfile-parse#69]
Hey,

it seems like there is something wrong with [this line](https://github.com/DBuildService/dockerfile-parse/blob/master/dockerfile_parse/parser.py#L196):

```python
>>> import io
>>> from dockerfile_parse import DockerfileParser
>>> dfp = DockerfileParser(fileobj=io.StringIO())
>>> dfp.content = 'FROM test'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/env/lib/python3.7/site-packages/dockerfile_parse/parser.py", line 196, in content
    dockerfile.write(u2b(content))
TypeError: string argument expected, got 'bytes'
```

Probably a StringIO does not take `bytes` as an input (at least in Python 3).

**Comment by MartinBasti** [comment]
You are right, parser writes bytes into fp opened in textual mode, waht causes errors in py3. You may need to use BytesIO instead.

But I'm not sure if requiring bytes mode instead of textual mode is good and probably parser should be updated.

**Comment by c4tz** [comment]
Oh yes, it works with ByteIO. Thanks for the quick response!

Well, I'd be fine with it if this case would be documented or there would be an example on how to use the `fileobj` parameter in the README.md :)
